### ISSUE TITLE
Kategorilerde tüm li itemlerini tıklanabilir yapma

### ISSUE THREAD

**Issue by muhammedogz** [miratcan/internetguzeldir#21]
Sekmelerin üzerine gelince, tam linke tıklamak yerine, hover olduğu anda tıklanabilir olsa daha rahat bir kullanım sunabilir.

Jinja bilmiyorum ama `base.html.jinja2` içerisindeki style kısmında `ul.categories li` yu değişip `a` 'ya width attık mı tamamdır 😄 

Eğer olursa bi PR atıp destek olmak isterim.

**Comment by miratcan** [comment]
Güzel fikir, tabi olur. Çalıştırma konusunu açıklayan bir yazı paylaşacağım en kısa zamanda.
