### ISSUE TITLE
Rebuild.py dosyasının static typing desteklemesi gerekiyor.

### ISSUE THREAD

**Issue by miratcan** [miratcan/internetguzeldir#31]
mypy ile valide edebilir hale gelelim.

**Comment by Kadermiyanyedi** [comment]
Bu göreve talibim :)

**Comment by ahmetveburak** [comment]
Ahh benim de gozum ilk bunu kesmisti  @Kadermiyanyedi :D

**Comment by miratcan** [comment]
ben karışmam :)

**Comment by miratcan** [comment]
Bunu kadere veriyorum o zaman :o)

**Comment by miratcan** [comment]
@Kadermiyanyedi  ne oldu bu iş?

**Comment by Kadermiyanyedi** [comment]
@miratcan  üzerinde çalışıyorum, sadece akşamları biraz bakabildiğimden az uzadı yakında biter

**Comment by miratcan** [comment]
@Kadermiyanyedi  bu agir bir is, ben alayim sen daha basit bir sey bulursun

**Comment by Kadermiyanyedi** [comment]
Başladığım kadarını yarın Pr açayım üzerinden devam et istersen senin işin de hafifler

**Comment by miratcan** [comment]
Süper fikir

**Comment by Kadermiyanyedi** [comment]
https://github.com/miratcan/internetguzeldir/pull/43
Burada açtım PR yanlışlıklar olabilir kusura bakma :)

**Comment by miratcan** [comment]
Çok işe yaradı teşekkür ederim <3
