### ISSUE TITLE
Webdriver'ın multiplatform desteklememesi

### ISSUE THREAD

**Issue by ahmetveburak** [miratcan/internetguzeldir#38]
Bu sorunun yaşanma ihtimali nedir bilemiyorum fakat uygun görürsen Firefox veya Chrome ile çalışacak şekilde düzenleyebilirim ya da hangisi varsa onu kullansın da yapılabilir.

Bir de şimdi denerken farkettim, arama eklendikten sonra oluşturulan ss'te bozulma var gibi. Örnek:
![https-www-stateofthedapps-com html](https://user-images.githubusercontent.com/31131727/143933727-3846914b-b8da-45e6-a893-510a123a6c7b.png)

Selenium ile ilgili detaylar da readme'ye eklenmeli mi?

**Comment by miratcan** [comment]
çok mantıklı evet

**Comment by ahmetveburak** [comment]
Tamamdir abi bana assign edebilirsin
