### ISSUE TITLE
NamedTemporaryFile Windows ile uyumlu calisamiyor

### ISSUE THREAD

**Issue by ahmetveburak** [miratcan/InternetGuzeldir#41]
Windows'ta projeyi calistiramiyordum sebebi suymus:
_Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later)._
https://docs.python.org/3.9/library/tempfile.html#tempfile.NamedTemporaryFile

Windows uyumlu olmasi isteniyorsa dosya manuel olarak silebilir ya da su linkteki gibi custom implementation kullanilabilir (henuz denenmedi)
https://stackoverflow.com/a/63173312/12306993

**Comment by miratcan** [comment]
Bunu sen halledebilir misin? Bende windows olmadığı için yapsam da test edemiyorum.

**Comment by ahmetveburak** [comment]
Tabi, denk gelmisken issue acayim dedim. Uygun bir vakitte tamamlarim.
